--- #YAML:1.0
name:                Parse-Marpa
version:             0.001_064
abstract:            (pre-Alpha) Earley's algorithm, plus LR(0) precomputation and predictive lexing
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Test::More:                    0
recommends:
    Test::Weaken            0.002002
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jeffrey Kegler
