--- #YAML:1.0
name:                Parse-Marpa
version:             1.001_005
abstract:            Generate Parsers from any BNF grammar
author:              
    - Jeffrey Kegler
generated_by:        Jeffrey Kegler
license: perl
distribution_type:   module
no_index:
    directory:
        - inc
        - t
        - example
        - bootstrap
        - author.t
        - save
    namespace:
        - Parse::Marpa::Internal
    package:
        - Parse::Marpa::Offset
requires:     
    Test::More:                    0
provides:
    Parse::Marpa:
        file: lib/Parse/Marpa.pm
        version: 1.001_005
    Parse::Marpa::Evaluator:
        file: lib/Parse/Marpa/Evaluator.pm
        version: 1.001_005
    Parse::Marpa::Recognizer:
        file: lib/Parse/Marpa/Recognizer.pm
        version: 1.001_005
    Parse::Marpa::Grammar:
        file: lib/Parse/Marpa/Grammar.pm
        version: 1.001_005
    Parse::Marpa::MDL:
        file: lib/Parse/Marpa/MDL.pm
        version: 1.001_005
    Parse::Marpa::Lex:
        file: lib/Parse/Marpa/Lex.pm
        version: 1.001_005
recommends:
    Test::Weaken: 1.000000
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
resources:
    license: http://dev.perl.org/licenses/
